In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
movies_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Desktop/SCALER-20240901T061051Z-001/SCALER/MODULE 13 Time Series & Recommendation/Business case study/FINAL/Zee recommender/Dataset/zee-movies.dat", encoding='latin-1', sep='::', header=None, names=['Movie ID', 'Title', 'Genres'], engine='python')
display(movies_df.head())

   Movie ID                     Title                        Genres
0  Movie ID                     Title                        Genres
1         1          Toy Story (1995)   Animation|Children's|Comedy
2         2            Jumanji (1995)  Adventure|Children's|Fantasy
3         3   Grumpier Old Men (1995)                Comedy|Romance
4         4  Waiting to Exhale (1995)                  Comedy|Drama

In [4]:
ratings_df = pd.read_csv("/content/drive/Othercomputers/My Laptop/Desktop/SCALER-20240901T061051Z-001/SCALER/MODULE 13 Time Series & Recommendation/Business case study/FINAL/Zee recommender/Dataset/zee-ratings.dat", encoding='latin-1', sep='::', header=None, engine='python')
display(ratings_df.head())

        0        1       2          3
0  UserID  MovieID  Rating  Timestamp
1       1     1193       5  978300760
2       1      661       3  978302109
3       1      914       3  978301968
4       1     3408       4  978300275

In [5]:
user_df= pd.read_csv("/content/drive/Othercomputers/My Laptop/Desktop/SCALER-20240901T061051Z-001/SCALER/MODULE 13 Time Series & Recommendation/Business case study/FINAL/Zee recommender/Dataset/zee-users.dat", encoding='latin-1', sep='::', header=None, names=['UserID', 'Gender', 'Age','Occupation','Zip-code'], engine='python')
user_df

      UserID  Gender  Age  Occupation  Zip-code
0     UserID  Gender  Age  Occupation  Zip-code
1          1       F    1          10     48067
2          2       M   56          16     70072
3          3       M   25          15     55117
4          4       M   45           7     02460
...      ...     ...  ...         ...       ...
6036    6036       F   25          15     32603
6037    6037       F   45           1     76006
6038    6038       F   56           1     14706
6039    6039       F   45           0     01060
6040    6040       M   25           6     11106

[6041 rows x 5 columns]

## Problem Statement

Creating a Recommender System to show personalized movie recommendations based on ratings given by a user and other users similar to them in order to improve user experience.

In [6]:
movies_df = movies_df.drop(0,axis = 0)
user_df  = user_df.drop(0,axis =0)
ratings_df = ratings_df.drop(0,axis =0 )

In [7]:
ratings_df = ratings_df.rename(columns = {0:'UserID',1:'MovieID',2:'Rating',3:'Timestamp'})

In [8]:
user_df

     UserID Gender Age Occupation Zip-code
1         1      F   1         10    48067
2         2      M  56         16    70072
3         3      M  25         15    55117
4         4      M  45          7    02460
5         5      M  25         20    55455
...     ...    ...  ..        ...      ...
6036   6036      F  25         15    32603
6037   6037      F  45          1    76006
6038   6038      F  56          1    14706
6039   6039      F  45          0    01060
6040   6040      M  25          6    11106

[6040 rows x 5 columns]

In [9]:
ratings_df

        UserID MovieID Rating  Timestamp
1            1    1193      5  978300760
2            1     661      3  978302109
3            1     914      3  978301968
4            1    3408      4  978300275
5            1    2355      5  978824291
...        ...     ...    ...        ...
1000205   6040    1091      1  956716541
1000206   6040    1094      5  956704887
1000207   6040     562      5  956704746
1000208   6040    1096      4  956715648
1000209   6040    1097      4  956715569

[1000209 rows x 4 columns]

In [10]:
movies_df

,Movie ID,Title,Genres
1,1,Toy Story (1995),Animation|Children's|Comedy
2,2,Jumanji (1995),Adventure|Children's|Fantasy
3,3,Grumpier Old Men (1995),Comedy|Romance
4,4,Waiting to Exhale (1995),Comedy|Drama
5,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3879,3948,Meet the Parents (2000),Comedy
3880,3949,Requiem for a Dream (2000),Drama
3881,3950,Tigerland (2000),Drama
3882,3951,Two Family House (2000),Drama
3883,3952,"Contender, The (2000)",Drama|Thriller

In [11]:
user_df.to_csv("User_info.csv",index = False)

In [12]:
ratings_df.to_csv("zee_ratings.csv",index = False)

In [13]:
movies_df.to_csv("Movies_info.csv",index = False)

In [14]:
from google.colab import files
files.download("zee_ratings.csv")

In [15]:
movies_df.head(3)

  Movie ID                    Title                        Genres
1        1         Toy Story (1995)   Animation|Children's|Comedy
2        2           Jumanji (1995)  Adventure|Children's|Fantasy
3        3  Grumpier Old Men (1995)                Comedy|Romance

## Examine dataset structure, characteristics, and statistical summary

In [16]:
ratings_df.info(),movies_df.info(),user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 1 to 1000209
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   UserID     1000209 non-null  object
 1   MovieID    1000209 non-null  object
 2   Rating     1000209 non-null  object
 3   Timestamp  1000209 non-null  object
dtypes: object(4)
memory usage: 30.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 1 to 3883
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Movie ID  3883 non-null   object
 1   Title     3883 non-null   object
 2   Genres    3883 non-null   object
dtypes: object(3)
memory usage: 91.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 1 to 6040
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   object
 1   Gender      6040 non-null   object
 2   Age         6040 non-null   object
 3   Occupation  6040 non-null   object
 4   Zip-code    6040 non-null   object
dtypes: object(5)
memory usage: 236.1+ KB

(None, None, None)

UserID::Gender::Age::Occupation::Zip-code


Gender is denoted by a "M" for male and "F" for female

Age is chosen from the following ranges:

1: "Under 18"

18: "18-24"

25: "25-34"

35: "35-44"

45: "45-49"

50: "50-55"

56: "56+"

Occupation is chosen from the following choices:

0: "other" or not specified

1: "academic/educator"

2: "artist"

3: "clerical/admin"

4: "college/grad student"

5: "customer service"

6: "doctor/health care"

7: "executive/managerial"

8: "farmer"

9: "homemaker"

10: "K-12 student"

11: "lawyer"

12: "programmer"

13: "retired"

14: "sales/marketing"

15: "scientist"

16: "self-employed"

17: "technician/engineer"

18: "tradesman/craftsman"

19: "unemployed"

20: "writer"

MOVIES FILE DESCRIPTION

=========================================================================

Movie information is in the file "movies.dat" and is in the following format:

MovieID::Title::Genres

Titles are identical to titles provided by the IMDB (including year of release)

Genres are pipe-separated and are selected from the following genres:

Action

Adventure

Animation

Children's

Comedy

Crime

Documentary

Drama

Fantasy

Film-Noir

Horror

Musical

Mystery

Romance

Sci-Fi

Thriller

War

Western


Concepts Tested:

Recommender Engine

Collaborative Filtering (Item-based & User-based Approach)

Pearson Correlation

Nearest Neighbors using Cosine Similarity

Matrix Factorization

In [17]:
ratings_df.describe(include ='object')

         UserID  MovieID   Rating  Timestamp
count   1000209  1000209  1000209    1000209
unique     6040     3706        5     458455
top        4169     2858        4  975528402
freq       2314     3428   348971         30

In [18]:
movies_df.describe(include ='object')

       Movie ID                  Title Genres
count      3883                   3883   3883
unique     3883                   3883    301
top        3952  Contender, The (2000)  Drama
freq          1                      1    843

In [19]:
user_df.describe(include ='object')

       UserID Gender   Age Occupation Zip-code
count    6040   6040  6040       6040     6040
unique   6040      2     7         21     3439
top      6040      M    25          4    48104
freq        1   4331  2096        759       19

In [20]:
movies_df['Genres']

1        Animation|Children's|Comedy
2       Adventure|Children's|Fantasy
3                     Comedy|Romance
4                       Comedy|Drama
5                             Comedy
                    ...
3879                          Comedy
3880                           Drama
3881                           Drama
3882                           Drama
3883                  Drama|Thriller
Name: Genres, Length: 3883, dtype: object

## Data Preprocessing

Feature engineering,Data cleaning, Data Preprocessing, Data merging, Data imputation everthing is done under this hood

In [21]:
r_df = ratings_df.copy()

In [22]:
from datetime import datetime

In [23]:
datetime.fromtimestamp(1633072800)

datetime.datetime(2021, 10, 1, 7, 20)

In [24]:
r_df['Hour'] = r_df['Timestamp'].apply(lambda x: datetime.fromtimestamp(int(x)).hour)

In [25]:
r_df['Timestamp'] = r_df['Timestamp'].apply(lambda x: datetime.fromtimestamp(int(x)))

In [26]:
r_df['Rating_Year'] = r_df['Timestamp'].dt.year
r_df['Rating_Month'] = r_df['Timestamp'].dt.month
r_df['Rating_on_Weekend'] = (r_df['Timestamp'].dt.weekday >= 5).astype(int)

In [27]:
r_df.rename(columns={'Hour': 'Rating_hour'}, inplace=True)

In [28]:
r_df

,UserID,MovieID,Rating,Timestamp,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend
1,1,1193,5,2000-12-31 22:12:40,22,2000,12,1
2,1,661,3,2000-12-31 22:35:09,22,2000,12,1
3,1,914,3,2000-12-31 22:32:48,22,2000,12,1
4,1,3408,4,2000-12-31 22:04:35,22,2000,12,1
5,1,2355,5,2001-01-06 23:38:11,23,2001,1,1
...,...,...,...,...,...,...,...,...
1000205,6040,1091,1,2000-04-26 02:35:41,2,2000,4,0
1000206,6040,1094,5,2000-04-25 23:21:27,23,2000,4,0
1000207,6040,562,5,2000-04-25 23:19:06,23,2000,4,0
1000208,6040,1096,4,2000-04-26 02:20:48,2,2000,4,0
1000209,6040,1097,4,2000-04-26 02:19:29,2,2000,4,0

In [29]:
r_df.drop(columns ='Timestamp', inplace = True)

In [30]:
r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 1 to 1000209
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   UserID             1000209 non-null  object
 1   MovieID            1000209 non-null  object
 2   Rating             1000209 non-null  object
 3   Rating_hour        1000209 non-null  int64
 4   Rating_Year        1000209 non-null  int32
 5   Rating_Month       1000209 non-null  int32
 6   Rating_on_Weekend  1000209 non-null  int64
dtypes: int32(2), int64(2), object(3)
memory usage: 45.8+ MB

In [31]:
r_df['Rating'] = pd.to_numeric(r_df['Rating'])

In [32]:

r_df_gr = r_df.groupby('UserID')['Rating'].mean().round(2)

In [33]:
r_df_gr

UserID
1       4.19
10      4.11
100     3.03
1000    4.13
1001    3.65
        ...
995     3.90
996     3.94
997     3.93
998     4.12
999     3.19
Name: Rating, Length: 6040, dtype: float64

In [34]:
r_df_gr.rename('Avg_user_rating',inplace = True)

UserID
1       4.19
10      4.11
100     3.03
1000    4.13
1001    3.65
        ...
995     3.90
996     3.94
997     3.93
998     4.12
999     3.19
Name: Avg_user_rating, Length: 6040, dtype: float64

In [35]:
r_df

,UserID,MovieID,Rating,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend
1,1,1193,5,22,2000,12,1
2,1,661,3,22,2000,12,1
3,1,914,3,22,2000,12,1
4,1,3408,4,22,2000,12,1
5,1,2355,5,23,2001,1,1
...,...,...,...,...,...,...,...
1000205,6040,1091,1,2,2000,4,0
1000206,6040,1094,5,23,2000,4,0
1000207,6040,562,5,23,2000,4,0
1000208,6040,1096,4,2,2000,4,0
1000209,6040,1097,4,2,2000,4,0

In [36]:
r_df_gr2 = r_df.groupby('UserID')['Rating'].count()

In [37]:
r_df_gr2.rename('Total_user_ratingCount',inplace = True)

UserID
1        53
10      401
100      76
1000     84
1001    377
       ...
995      49
996     296
997      30
998     135
999     412
Name: Total_user_ratingCount, Length: 6040, dtype: int64

In [38]:
r_df_gr3 = r_df.groupby('MovieID')['Rating'].mean()

In [39]:
r_df_gr3.rename('Avg_movie_rating',inplace = True)

MovieID
1       4.146846
10      3.540541
100     3.062500
1000    3.050000
1002    4.250000
          ...
994     4.095556
996     2.906250
997     3.357143
998     3.010753
999     3.283217
Name: Avg_movie_rating, Length: 3706, dtype: float64

In [40]:
r_df_gr4 = r_df.groupby('MovieID')['Rating'].count()

In [41]:
r_df_gr4

MovieID
1       2077
10       888
100      128
1000      20
1002       8
        ...
994      450
996      256
997       28
998       93
999      286
Name: Rating, Length: 3706, dtype: int64

In [42]:
m_df = movies_df.copy()

In [43]:
m_df['Genres'] = m_df['Genres'].str.split('|')

In [44]:
m_df = m_df.explode('Genres')

In [45]:
m_df['Genres'] = m_df['Genres'].str.strip()

In [46]:
m_df

     Movie ID                       Title      Genres
1           1            Toy Story (1995)   Animation
1           1            Toy Story (1995)  Children's
1           1            Toy Story (1995)      Comedy
2           2              Jumanji (1995)   Adventure
2           2              Jumanji (1995)  Children's
...       ...                         ...         ...
3880     3949  Requiem for a Dream (2000)       Drama
3881     3950            Tigerland (2000)       Drama
3882     3951     Two Family House (2000)       Drama
3883     3952       Contender, The (2000)       Drama
3883     3952       Contender, The (2000)    Thriller

[6408 rows x 3 columns]

In [47]:
m_df = m_df.pivot(index ='Movie ID',columns = 'Genres',values ='Title')
m_df

Genres,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
Movie ID,,,,,,,,,,,,,,,,,,
1,NaN,NaN,Toy Story (1995),Toy Story (1995),Toy Story (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,GoldenEye (1995),GoldenEye (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GoldenEye (1995),NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,City Hall (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,City Hall (1996),NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,Curdled (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,NaN,NaN,NaN,NaN,"Associate, The (L'Associe)(1982)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Big Night (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,Last Man Standing (1996),NaN,NaN,NaN,NaN,NaN,NaN,Last Man Standing (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Last Man Standing (1996)
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Caught (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Caught (1996),NaN,NaN
998,Set It Off (1996),NaN,NaN,NaN,NaN,Set It Off (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,2 Days in the Valley (1996),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
m_df = ~m_df.isna()

In [49]:
m_df = m_df.astype(int)

In [50]:
m_df

Genres,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
Movie ID,,,,,,,,,,,,,,,,,,
1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
10,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
100,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
1000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1001,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
996,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
997,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
998,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [51]:
m_df.reset_index(inplace = True)

In [52]:
m_df.rename(columns ={'Movie ID' :'MovieID'},inplace = True)

In [53]:
m_df

Genres,MovieID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,100,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
3,1000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,1001,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,994,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3879,996,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3880,997,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
3881,998,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3882,999,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [54]:
r_df_gr

UserID
1       4.19
10      4.11
100     3.03
1000    4.13
1001    3.65
        ...
995     3.90
996     3.94
997     3.93
998     4.12
999     3.19
Name: Avg_user_rating, Length: 6040, dtype: float64

In [55]:
df_reg = r_df.merge(r_df_gr2,on = 'UserID')

In [56]:
df_reg = df_reg.merge(r_df_gr,on ='UserID')

In [57]:
df_reg

,UserID,MovieID,Rating,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating
0,1,1193,5,22,2000,12,1,53,4.19
1,1,661,3,22,2000,12,1,53,4.19
2,1,914,3,22,2000,12,1,53,4.19
3,1,3408,4,22,2000,12,1,53,4.19
4,1,2355,5,23,2001,1,1,53,4.19
...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,2,2000,4,0,341,3.58
1000205,6040,1094,5,23,2000,4,0,341,3.58
1000206,6040,562,5,23,2000,4,0,341,3.58
1000207,6040,1096,4,2,2000,4,0,341,3.58
1000208,6040,1097,4,2,2000,4,0,341,3.58

In [58]:
df_reg = df_reg.merge(r_df_gr3,on ='MovieID')

In [59]:
df_reg

,UserID,MovieID,Rating,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating
0,1,1193,5,22,2000,12,1,53,4.19,4.390725
1,1,661,3,22,2000,12,1,53,4.19,3.464762
2,1,914,3,22,2000,12,1,53,4.19,4.154088
3,1,3408,4,22,2000,12,1,53,4.19,3.863878
4,1,2355,5,23,2001,1,1,53,4.19,3.854375
...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,2,2000,4,0,341,3.58,2.793566
1000205,6040,1094,5,23,2000,4,0,341,3.58,3.731489
1000206,6040,562,5,23,2000,4,0,341,3.58,3.799163
1000207,6040,1096,4,2,2000,4,0,341,3.58,3.976744
1000208,6040,1097,4,2,2000,4,0,341,3.58,3.965183

In [60]:
df_reg = df_reg.merge(r_df_gr4,on = 'MovieID')

In [61]:
df_reg.head(3)

,UserID,MovieID,Rating_x,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating,Rating_y
0,1,1193,5,22,2000,12,1,53,4.19,4.390725,1725
1,1,661,3,22,2000,12,1,53,4.19,3.464762,525
2,1,914,3,22,2000,12,1,53,4.19,4.154088,636

In [62]:
df_reg.rename(columns ={'Rating_y' : 'Movie_ratingCount'},inplace = True)

In [63]:
df_reg

,UserID,MovieID,Rating_x,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating,Movie_ratingCount
0,1,1193,5,22,2000,12,1,53,4.19,4.390725,1725
1,1,661,3,22,2000,12,1,53,4.19,3.464762,525
2,1,914,3,22,2000,12,1,53,4.19,4.154088,636
3,1,3408,4,22,2000,12,1,53,4.19,3.863878,1315
4,1,2355,5,23,2001,1,1,53,4.19,3.854375,1703
...,...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,2,2000,4,0,341,3.58,2.793566,373
1000205,6040,1094,5,23,2000,4,0,341,3.58,3.731489,1229
1000206,6040,562,5,23,2000,4,0,341,3.58,3.799163,478
1000207,6040,1096,4,2,2000,4,0,341,3.58,3.976744,344
1000208,6040,1097,4,2,2000,4,0,341,3.58,3.965183,2269

In [64]:
m_df

Genres,MovieID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,100,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
3,1000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,1001,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,994,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3879,996,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
3880,997,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
3881,998,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3882,999,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [65]:
df_reg = df_reg.merge(m_df,on ='MovieID')

In [66]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 29 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   UserID                  1000209 non-null  object
 1   MovieID                 1000209 non-null  object
 2   Rating_x                1000209 non-null  int64
 3   Rating_hour             1000209 non-null  int64
 4   Rating_Year             1000209 non-null  int32
 5   Rating_Month            1000209 non-null  int32
 6   Rating_on_Weekend       1000209 non-null  int64
 7   Total_user_ratingCount  1000209 non-null  int64
 8   Avg_user_rating         1000209 non-null  float64
 9   Avg_movie_rating        1000209 non-null  float64
 10  Movie_ratingCount       1000209 non-null  int64
 11  Action                  1000209 non-null  int64
 12  Adventure               1000209 non-null  int64
 13  Animation               1000209 non-null  int64
 14  Children's              1000209 non-null  int64
 15  Comedy                  1000209 non-null  int64
 16  Crime                   1000209 non-null  int64
 17  Documentary             1000209 non-null  int64
 18  Drama                   1000209 non-null  int64
 19  Fantasy                 1000209 non-null  int64
 20  Film-Noir               1000209 non-null  int64
 21  Horror                  1000209 non-null  int64
 22  Musical                 1000209 non-null  int64
 23  Mystery                 1000209 non-null  int64
 24  Romance                 1000209 non-null  int64
 25  Sci-Fi                  1000209 non-null  int64
 26  Thriller                1000209 non-null  int64
 27  War                     1000209 non-null  int64
 28  Western                 1000209 non-null  int64
dtypes: float64(2), int32(2), int64(23), object(2)
memory usage: 213.7+ MB

In [67]:
df_reg.rename(columns = {'Rating_x':'Rating'},inplace = True)

In [68]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 29 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   UserID                  1000209 non-null  object
 1   MovieID                 1000209 non-null  object
 2   Rating                  1000209 non-null  int64
 3   Rating_hour             1000209 non-null  int64
 4   Rating_Year             1000209 non-null  int32
 5   Rating_Month            1000209 non-null  int32
 6   Rating_on_Weekend       1000209 non-null  int64
 7   Total_user_ratingCount  1000209 non-null  int64
 8   Avg_user_rating         1000209 non-null  float64
 9   Avg_movie_rating        1000209 non-null  float64
 10  Movie_ratingCount       1000209 non-null  int64
 11  Action                  1000209 non-null  int64
 12  Adventure               1000209 non-null  int64
 13  Animation               1000209 non-null  int64
 14  Children's              1000209 non-null  int64
 15  Comedy                  1000209 non-null  int64
 16  Crime                   1000209 non-null  int64
 17  Documentary             1000209 non-null  int64
 18  Drama                   1000209 non-null  int64
 19  Fantasy                 1000209 non-null  int64
 20  Film-Noir               1000209 non-null  int64
 21  Horror                  1000209 non-null  int64
 22  Musical                 1000209 non-null  int64
 23  Mystery                 1000209 non-null  int64
 24  Romance                 1000209 non-null  int64
 25  Sci-Fi                  1000209 non-null  int64
 26  Thriller                1000209 non-null  int64
 27  War                     1000209 non-null  int64
 28  Western                 1000209 non-null  int64
dtypes: float64(2), int32(2), int64(23), object(2)
memory usage: 213.7+ MB

In [69]:
user_df.head(2)

  UserID Gender Age Occupation Zip-code
1      1      F   1         10    48067
2      2      M  56         16    70072

In [70]:
#user_df.drop(columns =(['Avg_rating','Total_rating_count']),inplace = True)

In [71]:
#user_df

In [72]:
df_reg = df_reg.merge(user_df, on = 'UserID')

In [73]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 33 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   UserID                  1000209 non-null  object
 1   MovieID                 1000209 non-null  object
 2   Rating                  1000209 non-null  int64
 3   Rating_hour             1000209 non-null  int64
 4   Rating_Year             1000209 non-null  int32
 5   Rating_Month            1000209 non-null  int32
 6   Rating_on_Weekend       1000209 non-null  int64
 7   Total_user_ratingCount  1000209 non-null  int64
 8   Avg_user_rating         1000209 non-null  float64
 9   Avg_movie_rating        1000209 non-null  float64
 10  Movie_ratingCount       1000209 non-null  int64
 11  Action                  1000209 non-null  int64
 12  Adventure               1000209 non-null  int64
 13  Animation               1000209 non-null  int64
 14  Children's              1000209 non-null  int64
 15  Comedy                  1000209 non-null  int64
 16  Crime                   1000209 non-null  int64
 17  Documentary             1000209 non-null  int64
 18  Drama                   1000209 non-null  int64
 19  Fantasy                 1000209 non-null  int64
 20  Film-Noir               1000209 non-null  int64
 21  Horror                  1000209 non-null  int64
 22  Musical                 1000209 non-null  int64
 23  Mystery                 1000209 non-null  int64
 24  Romance                 1000209 non-null  int64
 25  Sci-Fi                  1000209 non-null  int64
 26  Thriller                1000209 non-null  int64
 27  War                     1000209 non-null  int64
 28  Western                 1000209 non-null  int64
 29  Gender                  1000209 non-null  object
 30  Age                     1000209 non-null  object
 31  Occupation              1000209 non-null  object
 32  Zip-code                1000209 non-null  object
dtypes: float64(2), int32(2), int64(23), object(6)
memory usage: 244.2+ MB

## Checking missing values

In [74]:
m_df.isna().sum()

Genres
MovieID        0
Action         0
Adventure      0
Animation      0
Children's     0
Comedy         0
Crime          0
Documentary    0
Drama          0
Fantasy        0
Film-Noir      0
Horror         0
Musical        0
Mystery        0
Romance        0
Sci-Fi         0
Thriller       0
War            0
Western        0
dtype: int64

In [75]:
user_df.isna().sum()

UserID        0
Gender        0
Age           0
Occupation    0
Zip-code      0
dtype: int64

In [76]:
ratings_df.isna().sum()

UserID       0
MovieID      0
Rating       0
Timestamp    0
dtype: int64

There are no missing values in any table

In [77]:
m_df.head(2)

Genres,MovieID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,10,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [78]:
user_df.head(2)

  UserID Gender Age Occupation Zip-code
1      1      F   1         10    48067
2      2      M  56         16    70072

In [79]:
ratings_df.head(2)

  UserID MovieID Rating  Timestamp
1      1    1193      5  978300760
2      1     661      3  978302109

# Building Regression Model

In [80]:
df_reg.head(2)

,UserID,MovieID,Rating,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Gender,Age,Occupation,Zip-code
0,1,1193,5,22,2000,12,1,53,4.19,4.390725,...,0,0,0,0,0,0,F,1,10,48067
1,1,661,3,22,2000,12,1,53,4.19,3.464762,...,0,0,0,0,0,0,F,1,10,48067

In [81]:
df_reg['Gender'] = df_reg['Gender'].map({'M':1,'F':0})

In [82]:
df_reg.head(2)

,UserID,MovieID,Rating,Rating_hour,Rating_Year,Rating_Month,Rating_on_Weekend,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Gender,Age,Occupation,Zip-code
0,1,1193,5,22,2000,12,1,53,4.19,4.390725,...,0,0,0,0,0,0,0,1,10,48067
1,1,661,3,22,2000,12,1,53,4.19,3.464762,...,0,0,0,0,0,0,0,1,10,48067

In [83]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 33 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   UserID                  1000209 non-null  object
 1   MovieID                 1000209 non-null  object
 2   Rating                  1000209 non-null  int64
 3   Rating_hour             1000209 non-null  int64
 4   Rating_Year             1000209 non-null  int32
 5   Rating_Month            1000209 non-null  int32
 6   Rating_on_Weekend       1000209 non-null  int64
 7   Total_user_ratingCount  1000209 non-null  int64
 8   Avg_user_rating         1000209 non-null  float64
 9   Avg_movie_rating        1000209 non-null  float64
 10  Movie_ratingCount       1000209 non-null  int64
 11  Action                  1000209 non-null  int64
 12  Adventure               1000209 non-null  int64
 13  Animation               1000209 non-null  int64
 14  Children's              1000209 non-null  int64
 15  Comedy                  1000209 non-null  int64
 16  Crime                   1000209 non-null  int64
 17  Documentary             1000209 non-null  int64
 18  Drama                   1000209 non-null  int64
 19  Fantasy                 1000209 non-null  int64
 20  Film-Noir               1000209 non-null  int64
 21  Horror                  1000209 non-null  int64
 22  Musical                 1000209 non-null  int64
 23  Mystery                 1000209 non-null  int64
 24  Romance                 1000209 non-null  int64
 25  Sci-Fi                  1000209 non-null  int64
 26  Thriller                1000209 non-null  int64
 27  War                     1000209 non-null  int64
 28  Western                 1000209 non-null  int64
 29  Gender                  1000209 non-null  int64
 30  Age                     1000209 non-null  object
 31  Occupation              1000209 non-null  object
 32  Zip-code                1000209 non-null  object
dtypes: float64(2), int32(2), int64(24), object(5)
memory usage: 244.2+ MB

In [84]:
model_1 = df_reg.copy()

In [85]:
model_1[['Age','Occupation']] = model_1[['Age','Occupation']].astype(int)

In [86]:
model_1.drop(columns = 'Zip-code',inplace = True)

In [87]:
X = model_1.drop(columns=[
    'UserID', 'MovieID', 'Rating',
    'Rating_hour', 'Rating_Year', 'Rating_Month', 'Rating_on_Weekend'
])
y = model_1['Rating']

In [88]:
X

,Total_user_ratingCount,Avg_user_rating,Avg_movie_rating,Movie_ratingCount,Action,Adventure,Animation,Children's,Comedy,Crime,...,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Gender,Age,Occupation
0,53,4.19,4.390725,1725,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,10
1,53,4.19,3.464762,525,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,1,10
2,53,4.19,4.154088,636,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,10
3,53,4.19,3.863878,1315,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,10
4,53,4.19,3.854375,1703,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000204,341,3.58,2.793566,373,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,25,6
1000205,341,3.58,3.731489,1229,0,0,0,0,0,0,...,0,0,1,0,0,1,0,1,25,6
1000206,341,3.58,3.799163,478,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,25,6
1000207,341,3.58,3.976744,344,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,25,6
1000208,341,3.58,3.965183,2269,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,25,6

In [89]:
X.shape,y.shape

((1000209, 25), (1000209,))

In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [91]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((800167, 25), (200042, 25), (800167,), (200042,))

In [92]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [93]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [94]:
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)**0.5

0.9082515656924914

- On an avg my rating is off by 0.90 units. Maybe this can be better.

## Recommendation system using AE

In [115]:
!gdown 1EsPvxcp5lzdltC3yLar1_laArmk9RZpw
!gdown 1DgdthLfHLIq3AnS4YAa1bne-OM90oHoD

Downloading...
From: https://drive.google.com/uc?id=1EsPvxcp5lzdltC3yLar1_laArmk9RZpw
To: /content/ratings.csv
100% 2.48M/2.48M [00:00<00:00, 135MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DgdthLfHLIq3AnS4YAa1bne-OM90oHoD
To: /content/movies.csv
100% 516k/516k [00:00<00:00, 97.8MB/s]

In [116]:
ratings = pd.read_csv('ratings.csv')

In [117]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [126]:
ratings = ratings_df.copy()

In [127]:
ratings['UserID'] = pd.to_numeric(ratings['UserID'])
ratings[ratings['UserID'] < 669]

       UserID  MovieID Rating  Timestamp
1           1     1193      5  978300760
2           1      661      3  978302109
3           1      914      3  978301968
4           1     3408      4  978300275
5           1     2355      5  978824291
...       ...      ...    ...        ...
99983     668      356      4  975635187
99984     668     2916      3  975635878
99985     668       47      4  975635729
99986     668       50      5  975635677
99987     668      379      4  975635589

[99987 rows x 4 columns]

In [132]:
ratings = ratings[ratings['UserID'] < 669]

In [152]:
ratings['Rating'] = pd.to_numeric(ratings['Rating'])
rm = ratings.pivot(index= 'MovieID',columns = 'UserID',values= 'Rating').fillna(0)

/tmp/ipykernel_716/2555136450.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings['Rating'] = pd.to_numeric(ratings['Rating'])

In [153]:
rm.head()

UserID,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
MovieID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,5.0,5.0,...,0.0,3.0,0.0,3.0,0.0,4.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [154]:
rm.shape

(3264, 668)

In [155]:
# sparsity of the data
(rm > 0).sum().sum()/(rm.shape[0]*rm.shape[1])

np.float64(0.04585819170482564)

Only 4.5 % values are filled

#### Splitting in train val

In [156]:
from sklearn.model_selection import train_test_split
train, val = train_test_split(rm,test_size = 0.2,random_state = 42)

In [163]:
X_train  = train.values
X_val = val.values

In [159]:
val.shape

(653, 668)

Training Auto Encoders

In [165]:
import keras
from keras import layers
input_movie = keras.Input(shape=(668,))
encoded = layers.Dense(512, activation='relu')(input_movie)
encoded = layers.Dense(256, activation='relu')(encoded)
encoded = layers.Dense(128, activation='relu')(encoded)

decoded = layers.Dense(256, activation='relu')(encoded)
decoded = layers.Dense(512, activation='relu')(decoded)
decoded = layers.Dense(668, activation='linear')(decoded)

In [166]:
autoencoder = keras.Model(input_movie,decoded)
autoencoder.compile(optimizer = 'Adam',loss='mean_squared_error')

In [168]:
autoencoder.fit(X_train, X_train,
                epochs=100,
                batch_size=256,
                shuffle=True,
                validation_data=(X_val, X_val))

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.5741 - val_loss: 0.5030
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.4982 - val_loss: 0.4866
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.4791 - val_loss: 0.4673
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.4538 - val_loss: 0.4451
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.4289 - val_loss: 0.4289
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.4103 - val_loss: 0.4174
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.3962 - val_loss: 0.4083
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.3841 - val_loss: 0.4019
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.3719 - val_loss: 0.3940
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.3612 - val_loss: 0.3904
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.3508 - val_loss: 0.3835
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3406 - val_loss: 0.3802
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.3311 - val_loss: 0.3758
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.3226 - val_loss: 0.3741
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 76ms/step - loss: 0.3153 - val_loss: 0.3747
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 0.3086 - val_loss: 0.3698
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 0.3004 - val_loss: 0.3677
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.2940 - val_loss: 0.3658
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.2862 - val_loss: 0.3640
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.2787 - val_loss: 0.3633
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.2727 - val_loss: 0.3625
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2668 - val_loss: 0.3654
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.2652 - val_loss: 0.3612
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.2563 - val_loss: 0.3581
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2496 - val_loss: 0.3592
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.2438 - val_loss: 0.3567
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.2399 - val_loss: 0.3568
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.2349 - val_loss: 0.3555
Epoch 29/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.2299 - val_loss: 0.3556
Epoch 30/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.2246 - val_loss: 0.3559
Epoch 31/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - loss: 0.2188 - val_loss: 0.3543
Epoch 32/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2147 - val_loss: 0.3541
Epoch 33/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.2102 - val_loss: 0.3540
Epoch 34/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.2074 - val_loss: 0.3543
Epoch 35/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2037 - val_loss: 0.3533
Epoch 36/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.2000 - val_loss: 0.3541
Epoch 37/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.1962 - val_loss: 0.3541
Epoch 38/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1948 - val_loss: 0.3547
Epoch 39/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 0.1934 - val_loss: 0.3564
Epoch 40/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - loss: 0.1904 - val_loss: 0.3556
Epoch 41/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.1877 - val_loss: 0.3560
Epoch 42/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.1854 - val_loss: 0.3560
Epoch 43/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.1821 - val_loss: 0.3553
Epoch 44/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.1788 - val_loss: 0.3558
Epoch 45/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1790 - val_loss: 0.3581
Epoch 46/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1753 - val_loss: 0.3563
Epoch 47/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1714 - val_loss: 0.3554
Epoch 48/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.1689 - val_loss: 0.3558
Epoch 49/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1666 - val_loss: 0.3575
Epoch 50/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1653 - val_loss: 0.3567
Epoch 51/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1639 - val_loss: 0.3572
Epoch 52/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1615 - val_loss: 0.3573
Epoch 53/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1605 - val_loss: 0.3593
Epoch 54/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1589 - val_loss: 0.3585
Epoch 55/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1563 - val_loss: 0.3583
Epoch 56/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - loss: 0.1540 - val_loss: 0.3588
Epoch 57/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1523 - val_loss: 0.3592
Epoch 58/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1513 - val_loss: 0.3595
Epoch 59/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 94ms/step - loss: 0.1493 - val_loss: 0.3604
Epoch 60/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - loss: 0.1477 - val_loss: 0.3605
Epoch 61/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.1489 - val_loss: 0.3616
Epoch 62/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 81ms/step - loss: 0.1466 - val_loss: 0.3613
Epoch 63/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.1441 - val_loss: 0.3595
Epoch 64/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - loss: 0.1421 - val_loss: 0.3609
Epoch 65/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1407 - val_loss: 0.3612
Epoch 66/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.1397 - val_loss: 0.3617
Epoch 67/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1380 - val_loss: 0.3622
Epoch 68/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1364 - val_loss: 0.3627
Epoch 69/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1354 - val_loss: 0.3633
Epoch 70/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1347 - val_loss: 0.3640
Epoch 71/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - loss: 0.1336 - val_loss: 0.3651
Epoch 72/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - loss: 0.1322 - val_loss: 0.3639
Epoch 73/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1308 - val_loss: 0.3658
Epoch 74/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.1301 - val_loss: 0.3641
Epoch 75/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1289 - val_loss: 0.3664
Epoch 76/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1280 - val_loss: 0.3663
Epoch 77/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1287 - val_loss: 0.3661
Epoch 78/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1274 - val_loss: 0.3668
Epoch 79/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.1273 - val_loss: 0.3688
Epoch 80/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1267 - val_loss: 0.3679
Epoch 81/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 0.1258 - val_loss: 0.3688
Epoch 82/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 84ms/step - loss: 0.1247 - val_loss: 0.3681
Epoch 83/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.1228 - val_loss: 0.3682
Epoch 84/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 69ms/step - loss: 0.1213 - val_loss: 0.3681
Epoch 85/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 0.1203 - val_loss: 0.3693
Epoch 86/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.1197 - val_loss: 0.3702
Epoch 87/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - loss: 0.1191 - val_loss: 0.3700
Epoch 88/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - loss: 0.1187 - val_loss: 0.3712
Epoch 89/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1171 - val_loss: 0.3700
Epoch 90/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1155 - val_loss: 0.3717
Epoch 91/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1163 - val_loss: 0.3725
Epoch 92/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1157 - val_loss: 0.3733
Epoch 93/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.1150 - val_loss: 0.3731
Epoch 94/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1132 - val_loss: 0.3727
Epoch 95/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1127 - val_loss: 0.3732
Epoch 96/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - loss: 0.1121 - val_loss: 0.3747
Epoch 97/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.1130 - val_loss: 0.3766
Epoch 98/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.1169 - val_loss: 0.3752
Epoch 99/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - loss: 0.1153 - val_loss: 0.3753
Epoch 100/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - loss: 0.1126 - val_loss: 0.3740

In [169]:
autoencoder.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 668)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       342,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 256)            │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 512)            │       131,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 668)            │       342,684 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,042,134 (11.60 MB)

 Trainable params: 1,014,044 (3.87 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,028,090 (7.74 MB)

In [172]:
autoencoder.layers[3].output

Layer number 4 returns the latent space emebddings.

Let's create a model with
- input as model input and
- output as layer 4 output

In [173]:
intermediate_model = keras.Model(autoencoder.input, autoencoder.layers[3].output)

In [179]:
embeddings= intermediate_model.predict(rm.values)

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

In [180]:
embeddings.shape

(3264, 128)

In [181]:
embeddings[10]

array([ 0.        , 11.1238165 ,  6.871785  ,  8.169119  ,  0.        ,
        0.        ,  0.        ,  8.607572  ,  0.        ,  0.        ,
        0.        ,  0.        , 15.538248  ,  5.0270925 ,  7.768823  ,
        1.1824143 ,  0.        ,  5.8871007 ,  0.        ,  0.        ,
       12.577888  ,  0.9638936 ,  0.        ,  0.        ,  0.        ,
        0.        ,  7.092974  ,  0.        ,  0.75754434,  0.        ,
        0.        ,  1.6791207 , 19.3059    ,  0.        ,  4.1042647 ,
        0.        ,  0.        ,  1.0782413 ,  0.        ,  4.8853316 ,
        0.        ,  3.7143998 ,  0.        , 10.198844  ,  4.5665507 ,
        7.6016326 , 12.664319  , 16.367764  , 12.836931  ,  0.        ,
       15.359682  , 11.800433  ,  8.4059925 ,  6.9457884 ,  0.        ,
       14.883636  ,  1.4680076 ,  8.176274  , 22.578606  ,  0.        ,
       18.390268  ,  0.        ,  0.        , 15.507374  ,  0.        ,
        6.176912  ,  0.        , 10.133795  ,  0.        ,  0.        ,
        0.        ,  3.5418546 , 16.963045  ,  0.        ,  0.        ,
        2.863496  , 12.523631  ,  6.5521417 ,  0.        ,  0.        ,
        3.8173866 , 11.762407  , 16.134117  ,  0.        ,  5.7774634 ,
        0.        ,  0.        ,  0.        ,  0.        , 21.83337   ,
        5.57858   ,  0.        , 15.290424  , 14.134273  ,  0.        ,
        0.        ,  0.        , 13.312808  ,  8.66346   , 16.169239  ,
       13.520448  ,  0.        ,  0.        , 18.321365  ,  8.718596  ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.8363673 ,  0.        , 20.9607    ,  0.        ,  0.        ,
        7.149436  ,  0.        ,  0.        ,  6.756997  ,  0.5125901 ,
        0.        ,  9.042592  ,  9.444533  ,  7.51644   ,  0.        ,
        9.697348  ,  0.        , 12.246272  ], dtype=float32)

#### Finding similar movies - Cosine similarity

In [182]:
from sklearn.metrics.pairwise import cosine_similarity

In [183]:
similarity_matrix = cosine_similarity(embeddings)

In [184]:
similarity_matrix.shape

(3264, 3264)

In [185]:
item_sim_matrix = pd.DataFrame(similarity_matrix, index=rm.index, columns=rm.index)
item_sim_matrix.head() #Item-similarity Matrix

MovieID,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
MovieID,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.744042,0.717424,0.651259,0.702615,0.648215,0.724441,0.689462,0.696977,0.718683,...,0.562169,0.734089,0.745985,0.711248,0.623087,0.754058,0.554235,0.610566,0.552876,0.684890
2,0.744042,1.000000,0.720045,0.729750,0.737789,0.679779,0.703472,0.778509,0.756818,0.688554,...,0.657368,0.789546,0.775886,0.747899,0.731564,0.661638,0.589837,0.673091,0.667291,0.630645
3,0.717424,0.720045,1.000000,0.829921,0.848999,0.728319,0.855440,0.710230,0.798123,0.712389,...,0.631082,0.759912,0.657618,0.722869,0.743292,0.651357,0.548126,0.730551,0.653403,0.614312
4,0.651259,0.729750,0.829921,1.000000,0.830904,0.686588,0.837104,0.778752,0.797046,0.708046,...,0.677014,0.790708,0.729834,0.806341,0.790965,0.631803,0.574004,0.735104,0.769125,0.663388
5,0.702615,0.737789,0.848999,0.830904,1.000000,0.714140,0.873117,0.739266,0.780982,0.767262,...,0.650787,0.821135,0.749599,0.760472,0.756827,0.668768,0.594423,0.737277,0.720999,0.665022

#### Finding movies similar to Liar Liar

In [187]:
movies_df[movies_df.Title.str.contains('Liar Liar')]

      Movie ID             Title  Genres
1456      1485  Liar Liar (1997)  Comedy

In [193]:
item_sim_matrix[1485].sort_values(ascending = False).head(10)

MovieID
1485    1.000000
500     0.913591
586     0.909671
1020    0.907318
2027    0.899834
216     0.893432
231     0.888955
2124    0.879666
5       0.879663
3247    0.879064
Name: 1485, dtype: float32

In [195]:
movies_df

,Movie ID,Title,Genres
1,1,Toy Story (1995),Animation|Children's|Comedy
2,2,Jumanji (1995),Adventure|Children's|Fantasy
3,3,Grumpier Old Men (1995),Comedy|Romance
4,4,Waiting to Exhale (1995),Comedy|Drama
5,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3879,3948,Meet the Parents (2000),Comedy
3880,3949,Requiem for a Dream (2000),Drama
3881,3950,Tigerland (2000),Drama
3882,3951,Two Family House (2000),Drama
3883,3952,"Contender, The (2000)",Drama|Thriller

In [199]:
movies_df[movies_df['Movie ID'].isin(item_sim_matrix[1485].sort_values(ascending = False).head(10).index)]

      Movie ID                               Title             Genres
5            5  Father of the Bride Part II (1995)             Comedy
215        216                Billy Madison (1995)             Comedy
229        231                Dumb & Dumber (1994)             Comedy
497        500               Mrs. Doubtfire (1993)             Comedy
583        586                   Home Alone (1990)  Children's|Comedy
1008      1020                Cool Runnings (1993)             Comedy
1456      1485                    Liar Liar (1997)             Comedy
1959      2027                       Mafia! (1998)       Comedy|Crime
2056      2124           Addams Family, The (1991)             Comedy
3179      3247                   Sister Act (1992)       Comedy|Crime

# Matrix Factorization

In [95]:
ratings_df

        UserID MovieID Rating  Timestamp
1            1    1193      5  978300760
2            1     661      3  978302109
3            1     914      3  978301968
4            1    3408      4  978300275
5            1    2355      5  978824291
...        ...     ...    ...        ...
1000205   6040    1091      1  956716541
1000206   6040    1094      5  956704887
1000207   6040     562      5  956704746
1000208   6040    1096      4  956715648
1000209   6040    1097      4  956715569

[1000209 rows x 4 columns]

In [96]:
ratings_df["MovieID"] = ratings_df["MovieID"].astype(int)

In [97]:
movies_df["Movie ID"] = movies_df["Movie ID"].astype(int)

In [98]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 1 to 3883
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Movie ID  3883 non-null   int64
 1   Title     3883 non-null   object
 2   Genres    3883 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.1+ KB

In [99]:
#ratings_df_subset= ratings_df.copy()
ratings_df_subset= ratings_df.iloc[:100000]

In [100]:
ratings_subset = ratings_df_subset.copy()

In [101]:
!pip install cmfrec

Collecting cmfrec
  Downloading cmfrec-3.5.1.post13.tar.gz (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 6.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython in /usr/local/lib/python3.12/dist-packages (from cmfrec) (3.0.12)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from cmfrec) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from cmfrec) (1.16.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from cmfrec) (2.2.2)
Collecting findblas (from cmfrec)
  Using cached findblas-0.1.26.post1-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->cmfrec) (1.17.0)
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (pyproject.toml) ... canceled
ERROR: Operation cancelled by user

In [102]:
ratings_subset.drop(columns = 'Timestamp',inplace = True)

In [103]:
ratings_subset.rename(columns ={'UserID':'UserId','MovieID':'ItemId','Rating':'Rating'},inplace = True)
# Lib requires specific column names

In [104]:
ratings_subset.head(90)

   UserId  ItemId Rating
1       1    1193      5
2       1     661      3
3       1     914      3
4       1    3408      4
5       1    2355      5
..    ...     ...    ...
86      2    1259      5
87      2    3147      5
88      2    1544      4
89      2    1293      5
90      2    1188      4

[90 rows x 3 columns]

In [105]:
#creating user item matrix
ratings_subset['Rating'] = pd.to_numeric(ratings_subset['Rating'])
user_item_matrix = ratings_subset.pivot(index = 'UserId',columns ='ItemId',values = 'Rating').fillna(0)

In [106]:
user_item_matrix.head(2)

ItemId,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserId,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,5.0,5.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0

In [107]:
user_item_matrix.index = user_item_matrix.index.astype(int)
user_item_matrix.columns = user_item_matrix.columns.astype(int)

user_item_matrix = user_item_matrix.sort_index(axis=0)
user_item_matrix = user_item_matrix.sort_index(axis=1)

In [108]:
user_item_matrix

ItemId,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
UserId,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
((user_item_matrix > 0).sum().sum())/(user_item_matrix.shape[0] *user_item_matrix.shape[1])*100

np.float64(4.579559776077845)

- Only 4.5% of the values are filled

In [110]:
ratings_subset

       UserId  ItemId  Rating
1           1    1193       5
2           1     661       3
3           1     914       3
4           1    3408       4
5           1    2355       5
...       ...     ...     ...
99996     669     585       4
99997     669     586       3
99998     669     587       3
99999     669     588       4
100000    669     589       5

[100000 rows x 3 columns]

In [111]:
from cmfrec import CMF
model_lib = CMF(method="als", k=80, lambda_=0.1, verbose=True) # k=10 latent factors --> Dimensions
model_lib.fit(ratings_subset)

ModuleNotFoundError: No module named 'cmfrec'

In [ ]:
print(hasattr(model_lib, "item_mapping_"))  # Should be True
print(hasattr(model_lib, "user_mapping_"))  # Should be True

In [ ]:
ratings_subset

In [ ]:
# for streamlit csv
ratings_subset.to_csv("zee-ratings.csv",index = False)

In [ ]:
# for streamlit csv
from google.colab import files
files.download("zee-ratings.csv")

In [ ]:
# for streamlit csv
movies_susbet = movies_df[ratings_subset['ItemId'].isin(movies_df['Movie ID'])]

In [ ]:
movies_susbet

In [ ]:
movies_susbet.columns

In [ ]:

movies_susbet["Movie ID"] = movies_susbet["Movie ID"].astype(int)

In [ ]:
movies_susbet.to_csv("movies_info.csv",index = False)

In [ ]:
from google.colab import files
files.download("Movies_info.csv")

In [ ]:
# for streamlit csv

In [ ]:
# for streamlit csv

In [ ]:
movies_df

In [ ]:
model_lib.A_.shape

In [ ]:
model_lib.B_.shape

In [ ]:
# Get all predicted ratings
all_preds = np.dot(model_lib.A_,model_lib.B_.T)+ model_lib.glob_mean_

In [ ]:
# actual Ratings
actual = user_item_matrix.values[user_item_matrix>0]

In [ ]:
actual.shape

In [ ]:
mask = user_item_matrix>0

In [ ]:
all_preds[mask].shape

In [ ]:
prediction = all_preds[mask]

In [ ]:
# Calculate RMSE
from sklearn.metrics import mean_squared_error as mse
rmse_lib = mse(actual,prediction)**.5
print(f"RMSE (from library): {rmse_lib:.4f}")

In [ ]:
# Precision @ k

In [ ]:
movies_df.head(2)

In [ ]:
#top_items = model_lib.topN(user=1, n=5)

In [ ]:
#model_lib.topN(user=271, n=10)

In [ ]:
#print(user in model_lib.user_mapping_)

In [ ]:
import numpy as np
import pandas as pd

overlap_scores = []

for user in ratings_subset.UserId.unique():
    try:
        recommended = model_lib.topN(user=user, n=100)

        user_rated = ratings_subset.loc[ratings_subset.UserId == user, 'ItemId']

        relevant_items = ratings_subset.loc[
            (ratings_subset.UserId == user) & (ratings_subset.Rating >= 3), 'ItemId'
        ]

        valid_rec = set(recommended).intersection(set(user_rated))
        score = len(set(recommended).intersection(set(relevant_items))) / len(valid_rec)
        overlap_scores.append(score)

    except:
        overlap_scores.append(0)

overlap_scores = np.array(overlap_scores)
print("Average overlap:", overlap_scores.mean())
pd.Series(overlap_scores).hist(bins=20)

In [ ]:
overlap= []
num_rec = []
n = 10
for user in ratings_subset.UserId.unique():
    top_items = model_lib.topN(user=user, n=n)
    user_movies = ratings_subset.loc[(ratings_subset.UserId==user)].ItemId
    valid_rec = set(top_items).intersection(set(user_movies)) # I can only measure by what was in the training data

    _ = len(set(ratings_subset.loc[ratings_subset.UserId==user].sort_values(by='Rating', ascending=False).head(n).ItemId).intersection(set(valid_rec)))
    overlap.append(_)
    num_rec.append(len(valid_rec))

print('avg_perc_overlap:', np.array(overlap).mean() / np.array(num_rec).mean())
pd.Series(overlap).hist(bins=20)

## Saving the model

In [ ]:
# saving the model
import pickle

pickle_out = open("Recommender.pkl",mode ='wb')
pickle.dump(model_lib,pickle_out)
pickle_out.close()

In [ ]:
from google.colab import files
files.download("Recommender.pkl")